package br.trindade.androidbasics.ui.fragment;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.android.volley.AuthFailureError;
import com.android.volley.NetworkError;
import com.android.volley.NoConnectionError;
import com.android.volley.ParseError;
import com.android.volley.ServerError;
import com.android.volley.TimeoutError;
import com.android.volley.VolleyError;

import java.util.ArrayList;

import br.trindade.androidbasics.adapter.AdapterMovies;
import br.trindade.androidbasics.callback.BoxOfficeMoviesLoadedListener;
import br.trindade.androidbasics.database.DBMovies;
import br.trindade.androidbasics.model.Movie;
import br.trindade.androidbasics.task.TaskLoadMoviesBoxOffice;
import br.trindade.androidbasics.ui.R;
import br.trindade.androidbasics.util.BasicsApplication;

/**
 * A simple {@link Fragment} subclass.
 * Use the {@link BoxOfficeFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class BoxOfficeFragment extends Fragment implements BoxOfficeMoviesLoadedListener {

    //The key used to store arraylist of movie objects to and from parcelable
    private static final String STATE_MOVIES = "state_movies";

    //the arraylist containing our list of box office his
    private ArrayList<Movie> mListMovies = new ArrayList<>();

    //the adapter responsible for displaying our movies within a RecyclerView
    private AdapterMovies mAdapter;

    //the recyclerview containing showing all our movies
    private RecyclerView mRecyclerMovies;

    //the TextView containing error messages generated by Volley
    private TextView mTextError;

    public BoxOfficeFragment() {
        // Required empty public constructor
    }

    public static BoxOfficeFragment newInstance() {
        BoxOfficeFragment fragment = new BoxOfficeFragment();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View layout = inflater.inflate(R.layout.fragment_box_office, container, false);
        mTextError = (TextView) layout.findViewById(R.id.textVolleyError);
        mRecyclerMovies = (RecyclerView) layout.findViewById(R.id.listMovieHits);
        //set the layout manager before trying to display data
        mRecyclerMovies.setLayoutManager(new LinearLayoutManager(getActivity()));
        mAdapter = new AdapterMovies(getActivity());
        mRecyclerMovies.setAdapter(mAdapter);

        if (savedInstanceState != null) {
            //if this fragment starts after a rotation or configuration change, load the existing movies from a parcelable
            mListMovies = savedInstanceState.getParcelableArrayList(STATE_MOVIES);
        } else {
            //if this fragment starts for the first time, load the list of movies from a database
            mListMovies = BasicsApplication.getWritableDatabase().readMovies(DBMovies.BOX_OFFICE);
            //if the database is empty, trigger an AsycnTask to download movie list from the web
            if (mListMovies.isEmpty()) {
                new TaskLoadMoviesBoxOffice(this).execute();
            }
        }
        //update your Adapter to containg the retrieved movies
        mAdapter.setMovies(mListMovies);
        return layout;
    }


    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        //save the movie list to a parcelable prior to rotation or configuration change
        outState.putParcelableArrayList(STATE_MOVIES, mListMovies);
    }


    private void handleVolleyError(VolleyError error) {
        //if any error occurs in the network operations, show the TextView that contains the error message
        mTextError.setVisibility(View.VISIBLE);
        if (error instanceof TimeoutError || error instanceof NoConnectionError) {
            mTextError.setText(R.string.error_timeout);

        } else if (error instanceof AuthFailureError) {
            mTextError.setText(R.string.error_auth_failure);
        } else if (error instanceof ServerError) {
            mTextError.setText(R.string.error_auth_failure);
        } else if (error instanceof NetworkError) {
            mTextError.setText(R.string.error_network);
        } else if (error instanceof ParseError) {
            mTextError.setText(R.string.error_parser);
        }
    }

    /**
     * Called when the AsyncTask finishes load the list of movies from the web
     */
    @Override
    public void onBoxOfficeMoviesLoaded(ArrayList<Movie> listMovies) {
        mAdapter.setMovies(listMovies);
    }
}

